### ISSUE TITLE
Need the ground truth graph of HEPAR2 dataset

### ISSUE THREAD

**Issue by UzmaHasan** [aditya95sriram/bn-slim#2]
Hi. Thanks for creating such a comprehensive repository!

I need the HEPAR2 graph. I found it in bnlearn package but the picture is in png format and very unclear. I can not figure out the edge links from that image. https://www.bnlearn.com/bnrepository/discrete-large.html#hepar2

Can you please provide a clear picture or a csv file of the ground truth graph of HEPAR2 dataset??

**Comment by aditya95sriram** [comment]
Hi,

_Just to be clear, this isn't an issue pertaining the source code/software contained in this repository._

To answer your question, the bnlearn repository provides the images just as a visual aid and I think you're not expected to re-construct the graph manually by looking at the images. The repository provides the networks (that you see in the png) in several formats (links to the right of the image: BIF, DSC, NET, RDA, RDS). In my case, I worked with the `.net` files which are fairly simple to parse (see `read_net` function in [`bnio.py`](https://github.com/aditya95sriram/bn-slim/blob/github/bnio.py#L85) for a prototype implementation). 

Since you mention csv files I suspect you might be looking for the samples/instances and not the network itself. In which case, you could either generate the samples from the NET files using the `samge` tool of the BLIP package or use the instances/samples I generated (found [here](https://github.com/aditya95sriram/bn-slim/tree/github/datasets/dat)).

**Comment by UzmaHasan** [comment]
Thank you so much for the reply and clarification. It is really helpful and I appreciate it. Also, I really appreciate your highly enriched repository.
